adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ''
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 2.1.13
    packID: soc-framework-nist-ir
    _packName: SOC Framework NIST IR (800-61)
    prevname: ''
    supportedModules: []
    toServerVersion: ''
description: 'This playbook implements the NIST SP 800-61 Alert Response lifecycle in a structured, repeatable way. It serves
  as the top-level controller, orchestrating all downstream playbooks and automations that align to the four NIST phases:


  Preparation – Normalize and stage context (entities, products, alert categories) to ensure consistent execution.


  Detection & Analysis – Trigger enrichment and investigation playbooks (endpoint, network, identity, email, cloud) based
  on normalized entities and mapped MITRE ATT&CK tactics.


  Containment, Eradication, Recovery – Call the appropriate static or product-specific playbooks to contain threats, remove
  malicious artifacts, and restore systems.


  Post-Alert Activity – Document lessons learned, update playbook routing matrices, and feed back into SOC optimization.


  The design emphasizes modularity and flexibility:


  Each NIST phase is represented as a dedicated section or sub-playbook, making it easy to swap out or extend tools.


  Normalization (Upon Trigger of the EntryPoint) ensures entities (hosts, users, IPs, processes, etc.) are handled consistently.


  This top-level playbook is the backbone of the SOC Framework: it receives the alert trigger, applies the NIST 800-61 model,
  and routes execution to the appropriate detection, containment, and response sub-playbooks for standardized alert handling'
id: SOC NIST IR (800-61)_V3
inputs: []
name: SOC NIST IR (800-61)_V3
outputs: []
starttaskid: '0'
tags:
- SOC_Framework_Unified
- SOC
tasks:
  '0':
    continueonerrortype: ''
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 4b81322f-09e6-4306-83e6-e3f95b45ec8c
      iscommand: false
      name: ''
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 4b81322f-09e6-4306-83e6-e3f95b45ec8c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    continueonerrortype: ''
    id: '1'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 707a43f2-ce32-449f-894f-a0516e802be0
      iscommand: false
      name: Preparation
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 707a43f2-ce32-449f-894f-a0516e802be0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 220\n  }\n}"
  '3':
    continueonerrortype: ''
    id: '3'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a8a79a1d-db10-42e4-8469-335dc3f7afef
      iscommand: false
      name: Detection & Analysis
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: a8a79a1d-db10-42e4-8469-335dc3f7afef
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 390\n  }\n}"
  '5':
    continueonerrortype: ''
    id: '5'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 82a21dcd-8822-4211-8370-bb5044a2661b
      iscommand: false
      name: Containment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 82a21dcd-8822-4211-8370-bb5044a2661b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 740\n  }\n}"
  '7':
    continueonerrortype: ''
    id: '7'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 467e83fc-5ad9-43fc-8808-94358e3e7c52
      iscommand: false
      name: Eradication
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 467e83fc-5ad9-43fc-8808-94358e3e7c52
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1090\n  }\n}"
  '9':
    continueonerrortype: ''
    id: '9'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7076683a-109c-4f3e-8714-c729eb5ef6ae
      iscommand: false
      name: Recovery
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 7076683a-109c-4f3e-8714-c729eb5ef6ae
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1440\n  }\n}"
  '11':
    continueonerrortype: ''
    id: '11'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0f6e6bd7-9427-4585-85ab-a6455d741e78
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 0f6e6bd7-9427-4585-85ab-a6455d741e78
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1790\n  }\n}"
  '13':
    continueonerrortype: ''
    id: '13'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: This playbook acts as a container for Containment playbooks acting on Product Category (i.e. EndPoint,
        Data, Network, Cloud SaaS, Cloud Workload, Identity).
      id: a496d4a7-564f-43e4-8c6d-b92eeaa462a3
      iscommand: false
      name: SOC Containment_V3
      playbookId: SOC Containment_V3
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: a496d4a7-564f-43e4-8c6d-b92eeaa462a3
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 910\n  }\n}"
  '14':
    continueonerrortype: ''
    id: '14'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      id: 76e167da-bd76-4689-8307-720610b53c4d
      iscommand: false
      name: SOC Analysis_V3
      playbookId: SOC Analysis_V3
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 76e167da-bd76-4689-8307-720610b53c4d
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 560\n  }\n}"
  '15':
    continueonerrortype: ''
    id: '15'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      id: d7088963-3f31-4f23-8006-8ce0197116c0
      iscommand: false
      name: SOC Eradication_V3
      playbookId: SOC Eradication_V3
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: d7088963-3f31-4f23-8006-8ce0197116c0
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1260\n  }\n}"
  '16':
    continueonerrortype: ''
    id: '16'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      id: 1bb50423-f0d1-4446-888b-ade2a1146870
      iscommand: false
      name: SOC Recovery_V3
      playbookId: SOC Recovery_V3
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 1bb50423-f0d1-4446-888b-ade2a1146870
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1610\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1900,\n      \"width\":\
  \ 380,\n      \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
fromversion: 5.0.0
