import demistomock as demisto
from CommonServerPython import *
import json


AI_PROMPT_TEMPLATE = """You are a senior SOC analyst writing a concise incident verdict for your team.

Write a 3-5 sentence plain-language summary of this identity threat incident.
Focus on: what happened, how confident we are, what the attacker likely did or tried to do,
and what the recommended next action is.

Do NOT use bullet points. Write in plain prose. Do NOT repeat field names or headers.
Write as if briefing a fellow analyst who needs to make a fast decision.

Incident data:
- Actor: {actor}
- Verdict: {verdict}
- Confidence: {confidence}
- Compromise level: {compromise_level}
- Compromise decision: {compromise_decision}
- Spread: {spread_level}
- MITRE tactic: {mitre_tactic}
- Auth failures in last 24h: {auth_failure_count}
- Identity provider events detected: {identity_events}
- Forwarding rules created: {forwarding_rules}
- Response recommended: {response_recommended}

Write the summary now:"""


def generate_ai_verdict(args: dict) -> CommandResults:
    """
    Calls the XSIAM AI Prompt task to generate a plain-language verdict summary.
    Writes the result to the warroom and stores it in Analysis.story.

    Architecture note:
      This is NOT an autonomous agent action. The AI explains the verdict.
      The analyst reads it and decides. The Agentic Assistant is available
      alongside for deeper investigation if the analyst chooses to engage it.

      Approved pattern per SOC Framework design decision:
        Analysis playbook → AI Prompt task (explains verdict) → warroom
        Analyst → Agentic Assistant (optional deeper investigation)

    Value Driver: VD3 — eliminates 3h manual triage pivot.
    Metric: MTTT — analyst time to confident decision target < 5 minutes.
    """

    actor = args.get('actor', 'unknown')
    verdict = args.get('verdict', 'suspicious')
    confidence = args.get('confidence', 'medium')
    compromise_level = args.get('compromise_level', 'medium')
    compromise_decision = args.get('compromise_decision', 'suspected')
    spread_level = args.get('spread_level', 'isolated')
    mitre_tactic = args.get('mitre_tactic', 'Credential Access')
    auth_failure_count = args.get('auth_failure_count', '0')
    identity_events = args.get('identity_events', 'none')
    forwarding_rules = args.get('forwarding_rules', '0')
    response_recommended = args.get('response_recommended', 'false')

    if isinstance(identity_events, list):
        identity_events = ', '.join(identity_events[:5]) if identity_events else 'none'

    prompt = AI_PROMPT_TEMPLATE.format(
        actor=actor,
        verdict=verdict,
        confidence=confidence,
        compromise_level=compromise_level,
        compromise_decision=compromise_decision,
        spread_level=spread_level,
        mitre_tactic=mitre_tactic,
        auth_failure_count=auth_failure_count,
        identity_events=identity_events,
        forwarding_rules=forwarding_rules,
        response_recommended=response_recommended,
    )

    # Call XSIAM's native AI Prompt capability
    try:
        ai_response = demisto.executeCommand(
            'core-ai-query',
            {'prompt': prompt, 'max_tokens': '300'}
        )

        if isError(ai_response[0]):
            story = _fallback_story(
                actor, verdict, confidence, compromise_level,
                mitre_tactic, response_recommended
            )
        else:
            story = ai_response[0].get('Contents', {}).get('response', '') or \
                    ai_response[0].get('HumanReadable', '')
            if not story:
                story = _fallback_story(
                    actor, verdict, confidence, compromise_level,
                    mitre_tactic, response_recommended
                )

    except Exception:
        story = _fallback_story(
            actor, verdict, confidence, compromise_level,
            mitre_tactic, response_recommended
        )

    # Write to warroom
    verdict_color = {
        'malicious': '🔴',
        'suspicious': '🟡',
        'benign': '🟢',
    }.get(verdict, '⚪')

    warroom_entry = (
        f"## {verdict_color} SOC Framework — Identity Verdict Summary\n\n"
        f"{story}\n\n"
        f"---\n"
        f"*Generated by SOC Framework AI Analysis · "
        f"Verdict: {verdict.upper()} · Confidence: {confidence} · "
        f"Containment {'recommended' if response_recommended == 'true' else 'not required'}*"
    )

    demisto.results({
        'Type': entryTypes['note'],
        'ContentsFormat': formats['markdown'],
        'Contents': warroom_entry,
        'HumanReadable': warroom_entry,
    })

    return CommandResults(
        outputs_prefix='Analysis',
        outputs={'story': story},
        readable_output=warroom_entry,
    )


def _fallback_story(actor, verdict, confidence, compromise_level,
                    mitre_tactic, response_recommended):
    """Fallback if AI call fails — structured but readable."""
    action = (
        "Containment actions have been prepared in Shadow Mode for analyst review."
        if response_recommended == 'true'
        else "No immediate containment action is required at this time."
    )
    return (
        f"Analysis of activity associated with {actor} indicates a {verdict} verdict "
        f"with {confidence} confidence. The observed signals are consistent with "
        f"{mitre_tactic} activity at a {compromise_level} compromise level. {action}"
    )


def main():
    try:
        args = demisto.args()
        result = generate_ai_verdict(args)
        return_results(result)
    except Exception as e:
        return_error(f'SOCFramework_AIVerdictSummary failed: {str(e)}')


if __name__ == '__builtin__' or __name__ == 'builtins':
    main()
