id: 84ec14f8-54f7-40a6-8c05-6acdc1f4fc48
version: 13
contentitemexportablefields:
  contentitemfields:
    packID: ""
    packName: SOC Framework Unified
    itemVersion: 3.1.4
    fromServerVersion: 5.0.0
    toServerVersion: ""
    definitionid: ""
    prevname: ""
    isoverridable: false
    supportedModules: []
vcShouldKeepItemLegacyProdMachine: false
name: SOC Containment Evaluation_V3
tags:
- SOC
- SOC_Framework_Unified
- Containment
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7e6a701e-667b-4a70-8a74-14564da75fc7
    type: start
    task:
      id: 7e6a701e-667b-4a70-8a74-14564da75fc7
      version: -1
      name: ""
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "31"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 6944e944-2ade-4f6d-b6e0-0f6b8e2c3253
    type: title
    task:
      id: 6944e944-2ade-4f6d-b6e0-0f6b8e2c3253
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 960
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "31":
    id: "31"
    taskid: ccfd4d07-3d48-4610-bf9d-9ed0f49551eb
    type: regular
    task:
      id: ccfd4d07-3d48-4610-bf9d-9ed0f49551eb
      version: -1
      name: Set Containment Status
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex XSOAR
        6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "32"
    scriptarguments:
      append:
        simple: "false"
      force:
        simple: "true"
      key:
        simple: Containment.status
      value:
        simple: ${inputs.status}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "32":
    id: "32"
    taskid: 7ba489bd-a62b-47f4-a5d4-2a157d7dd7fe
    type: regular
    task:
      id: 7ba489bd-a62b-47f4-a5d4-2a157d7dd7fe
      version: -1
      name: Set Containment Isolated Hosts
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex XSOAR
        6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "44"
    scriptarguments:
      append:
        simple: "false"
      force:
        simple: "true"
      key:
        simple: Containment.isolate_hosts
      value:
        simple: ${inputs.isolated_hosts}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "43":
    id: "43"
    taskid: fde09d0c-93d8-423c-926d-5f0562365364
    type: regular
    task:
      id: fde09d0c-93d8-423c-926d-5f0562365364
      version: -1
      name: Set Story
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex XSOAR
        6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "false"
      force:
        simple: "true"
      key:
        simple: Containment.story
      value:
        simple: ${inputs.story}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 775
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "44":
    id: "44"
    taskid: db106c52-f407-4794-bfab-6545966cb9c1
    type: regular
    task:
      id: db106c52-f407-4794-bfab-6545966cb9c1
      version: -1
      name: Set Containment Action
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex XSOAR
        6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "43"
    scriptarguments:
      append:
        simple: "false"
      force:
        simple: "true"
      key:
        simple: Containment.action
      value:
        simple: ${inputs.action}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 970,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: status
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: isolated_hosts
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: story
  value:
    simple: |-
      Malware execution confirmed on ${Analysis.host_count} host(s).
      Spread level assessed as ${Analysis.spread_level}.
      Compromise level: ${Analysis.compromised_host_level}.
      Case risk score: ${Analysis.case_risk_score}.
      Containment action taken: ${Containment.action}.
      Hosts isolated: ${Containment.isolated_hosts}.
      Users disabled: ${Containment.disabled_users}.
  required: false
  description: ""
  playbookInputQuery: null
- key: action
  value:
    simple: isolate_host
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - status
  - isolated_hosts
  - story
  - action
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - Containment.status
  - Containment.isolate_hosts
  - Containment.story
  - Containment.action
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: Containment.status
  type: string
- contextPath: Containment.isolate_hosts
  type: unknown
- contextPath: Containment.story
  type: unknown
- contextPath: Containment.action
  type: unknown
sourceplaybookid: SOC Data Analysis_V3
dirtyInputs: true
adopted: true
